version: '3.0'
services:
  java-server:
    build: .
    depends_on:
      - market-bd
    ports:
      - "8081:8085"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://market-bd:5432/market
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=443966
  market-bd:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=market
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=443966
