CREATE TABLE IF NOT EXISTS users( id BIGINT PRIMARY KEY );

CREATE TABLE IF NOT EXISTS products(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, count INT NOT NULL, user_id BIGINT REFERENCES users(id));