version: '3.0'
services:
  java-app:
    build: .
    depends_on:
      - bd
    ports:
      - "8088:8082"
  bd:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=d6KTf*gFLnY^
      - MYSQL_DATABASE=mega-market
