package group.megamarket.gateway.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 */
@WebServiceClient(name = "StorageServiceImplService", targetNamespace = "http://localhost:8000/soap", wsdlLocation = "http://localhost:8000/soap?wsdl")
public class StorageServiceImplService
        extends Service {

    private final static URL STORAGESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STORAGESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName STORAGESERVICEIMPLSERVICE_QNAME = new QName("http://localhost:8000/soap", "StorageServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORAGESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        STORAGESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public StorageServiceImplService() {
        super(__getWsdlLocation(), STORAGESERVICEIMPLSERVICE_QNAME);
    }

    public StorageServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORAGESERVICEIMPLSERVICE_QNAME, features);
    }

    public StorageServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, STORAGESERVICEIMPLSERVICE_QNAME);
    }

    public StorageServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORAGESERVICEIMPLSERVICE_QNAME, features);
    }

    public StorageServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorageServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns StorageService
     */
    @WebEndpoint(name = "ProductPort")
    public StorageService getProductPort() {
        return super.getPort(new QName("http://localhost:8000/soap", "ProductPort"), StorageService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns StorageService
     */
    @WebEndpoint(name = "ProductPort")
    public StorageService getProductPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8000/soap", "ProductPort"), StorageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STORAGESERVICEIMPLSERVICE_EXCEPTION != null) {
            throw STORAGESERVICEIMPLSERVICE_EXCEPTION;
        }
        return STORAGESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
