version: '3.1'
services:
  storage-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - storage-db
    environment:
      - JDBC_URL=jdbc:postgresql://storage-db:5432/storage
      - JDBC_USERNAME=root
      - JDBC_PASSWORD=root
      - HIBERNATE_SHOW_SQL=false
      - USER_SERVICE_URL=http://localhost:8080/
  storage-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=storage
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root